# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplyWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 500)
        self.apply_title_label = QtWidgets.QLabel(Dialog)
        self.apply_title_label.setGeometry(QtCore.QRect(10, 10, 832, 51))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(30)
        self.apply_title_label.setFont(font)
        self.apply_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.apply_title_label.setObjectName("apply_title_label")
        self.locker_list = QtWidgets.QListWidget(Dialog)
        self.locker_list.setGeometry(QtCore.QRect(60, 120, 431, 311))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(14)
        self.locker_list.setFont(font)
        self.locker_list.setObjectName("locker_list")
        self.locker_list_label = QtWidgets.QLabel(Dialog)
        self.locker_list_label.setGeometry(QtCore.QRect(60, 90, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.locker_list_label.setFont(font)
        self.locker_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.locker_list_label.setObjectName("locker_list_label")
        self.applyBtn = QtWidgets.QPushButton(Dialog)
        self.applyBtn.setGeometry(QtCore.QRect(540, 300, 271, 141))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.applyBtn.setFont(font)
        self.applyBtn.setAutoDefault(False)
        self.applyBtn.setObjectName("applyBtn")
        self.name_label = QtWidgets.QLabel(Dialog)
        self.name_label.setGeometry(QtCore.QRect(550, 130, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.locker_label = QtWidgets.QLabel(Dialog)
        self.locker_label.setGeometry(QtCore.QRect(550, 190, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.locker_label.setFont(font)
        self.locker_label.setObjectName("locker_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.apply_title_label.setText(_translate("Dialog", "사물함 신청"))
        self.locker_list_label.setText(_translate("Dialog", "신청 가능한 사물함"))
        self.applyBtn.setText(_translate("Dialog", "신청하기"))
        self.name_label.setText(_translate("Dialog", "학생 이름 :"))
        self.locker_label.setText(_translate("Dialog", "선택한 사물함 :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
