# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 500)
        self.loginBtn = QtWidgets.QPushButton(Dialog)
        self.loginBtn.setGeometry(QtCore.QRect(400, 340, 150, 61))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.loginBtn.setFont(font)
        self.loginBtn.setAutoDefault(False)
        self.loginBtn.setObjectName("loginBtn")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setGeometry(QtCore.QRect(180, 40, 501, 31))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(24)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.title_label_2 = QtWidgets.QLabel(Dialog)
        self.title_label_2.setGeometry(QtCore.QRect(270, 70, 311, 71))
        font = QtGui.QFont()
        font.setFamily("BM Hanna 11yrs Old")
        font.setPointSize(48)
        self.title_label_2.setFont(font)
        self.title_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label_2.setObjectName("title_label_2")
        self.id_label = QtWidgets.QLabel(Dialog)
        self.id_label.setGeometry(QtCore.QRect(190, 200, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(24)
        self.id_label.setFont(font)
        self.id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.id_label.setObjectName("id_label")
        self.pw_label = QtWidgets.QLabel(Dialog)
        self.pw_label.setGeometry(QtCore.QRect(250, 270, 130, 61))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(24)
        self.pw_label.setFont(font)
        self.pw_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pw_label.setObjectName("pw_label")
        self.id_edit = QtWidgets.QLineEdit(Dialog)
        self.id_edit.setGeometry(QtCore.QRect(390, 210, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.id_edit.setFont(font)
        self.id_edit.setObjectName("id_edit")
        self.pw_edit = QtWidgets.QLineEdit(Dialog)
        self.pw_edit.setGeometry(QtCore.QRect(390, 280, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pw_edit.setFont(font)
        self.pw_edit.setObjectName("pw_edit")
        self.loginBtn_2 = QtWidgets.QPushButton(Dialog)
        self.loginBtn_2.setGeometry(QtCore.QRect(560, 340, 150, 61))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.loginBtn_2.setFont(font)
        self.loginBtn_2.setAutoDefault(False)
        self.loginBtn_2.setObjectName("loginBtn_2")
        self.registerBtn = QtWidgets.QPushButton(Dialog)
        self.registerBtn.setGeometry(QtCore.QRect(240, 340, 150, 61))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(18)
        self.registerBtn.setFont(font)
        self.registerBtn.setAutoDefault(False)
        self.registerBtn.setObjectName("registerBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginBtn.setText(_translate("Dialog", "로그인"))
        self.title_label.setText(_translate("Dialog", "소프트웨어융합대학 사물함 신청 시스템"))
        self.title_label_2.setText(_translate("Dialog", "LockerSpot"))
        self.id_label.setText(_translate("Dialog", "ON국민 아이디:"))
        self.pw_label.setText(_translate("Dialog", "비밀번호:"))
        self.loginBtn_2.setText(_translate("Dialog", "관리자 로그인"))
        self.registerBtn.setText(_translate("Dialog", "회원가입"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
